SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM (SELECT ANIMAL_ID, HOUR(DATETIME) AS HOUR
      FROM ANIMAL_OUTS
      WHERE HOUR(DATETIME)>=9 && HOUR(DATETIME)<20) AS SUB_QUERY
GROUP BY HOUR
ORDER BY HOUR