SELECT USED_TOTAL_SALES.USER_ID AS USER_ID, NICKNAME, TOTAL_SALES
FROM USED_GOODS_USER,(
    SELECT WRITER_ID AS USER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = "DONE"
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
    ) AS USED_TOTAL_SALES
WHERE USED_GOODS_USER.USER_ID = USED_TOTAL_SALES.USER_ID
ORDER BY TOTAL_SALES