-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/", USED_GOODS_BOARD.BOARD_ID, "/", FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH 
FROM USED_GOODS_FILE, USED_GOODS_BOARD
WHERE USED_GOODS_FILE.BOARD_ID = USED_GOODS_BOARD.BOARD_ID 
        AND USED_GOODS_BOARD.VIEWS = (SELECT MAX(VIEWS)
              FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC