SELECT REST_INFO.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO, 
    (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_VALUE
    FROM REST_INFO
    GROUP BY FOOD_TYPE) AS MAX_TABLE
WHERE REST_INFO.FOOD_TYPE=MAX_TABLE.FOOD_TYPE AND REST_INFO.FAVORITES=MAX_TABLE.MAX_VALUE
ORDER BY FOOD_TYPE DESC